#
# top-level Makefile -- just the build steps, see the Old/calvin
# 	 a Makefile for running tests

install:
	go install github.com/davecb/Play-it-Again-Sam/pkg/loadTesting
	go install github.com/davecb/Play-it-Again-Sam/cmd/runLoadTest
