#
# Copy binaries to ${TARGET}. This is for quick user installation.
# 	It requires ${TARGET} exists and copies the pre-made
# 	binaries there.
#
TARGET=/usr/local/bin

all:
	cp hull/hull mkLoadTestFiles/mkLoadTestFiles \
		runLoadTest/runLoadTest ../scripts/* ${TARGET}
