#!/bin/sh
#
# nginx2perf -- write a perf log from an nginx log
#	If it has a $request_time field, report it as latency
# 1          2 3 4                      5      6   7
# 10.110.2.1 - - [29/Mar/2017:06:36:22 -0400] "GET /magento/ ...
# 8         9   10
# HTTP/1.1" 304 0 "https://www.kobo.com/nz/en/category/romance-2" "Mozilla/5.0 (Linux; Android 5.1.1; SM-J200Y Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 KoboApp/7.1.20708 KoboPlatform Id/00000000-0000-0000-0000-000000004000 KoboAffiliate/Kobo KoboBuildFlavor/global" "0.012" 
ProgName=`basename $0`

main() {
	name=$1

	if [ $# -lt 1 ]; then
		say "$ProgName error: you must supply a parameter"
		say "Usage: $0 parameter"
		exit 1
	fi

	echo "#yyy-mm-dd hh:mm:ss latency xfertime thinktime bytes path rc op"
	cat $name |\
	awk '
	/.*/ {
		date = $4 # [29/Mar/2017:06:36:22
		sub("\\[", "", date)
		sub(":", " ", date)
		split(date, a, " ")
		date = a[1]
		time = a[2]
		split(date, a, "/")
		date = a[3] "-" a[2] "-" a[1]
		op = $6
		gsub("\"", "", op)
		path = $7
		rc = $9
		bytes = $10
		rt = $(NF)
		gsub("\"", "", rt)
		print date, time, rt, 0, 0, bytes, path, rc, op 
	}
'
}

say() {
	echo "$@" 1>&2
}

main "$@"
