#!/bin/sh
#
# nginx2perf -- write a perf log from an nginx log
#	If it has a $request_time field, report it as latency
# 1          2 3 4                      5      6   7
# 10.110.2.1 - - [29/Mar/2017:06:36:22 -0400] "GET /xxx/ ...
# 8         9   10 11 12            13
# HTTP/1.1" 304 0 "" "Mozilla/5.0" "0.012"
ProgName=`basename $0`

main() {
	name=$1

	if [ $# -lt 1 ]; then
		say "$ProgName error: you must supply a parameter"
		say "Usage: $0 parameter"
		exit 1
	fi

	echo "#yyy-mm-dd hh:mm:ss latency xfertime sleeptime bytes path rc op"
	cat $name |\
	awk '
	/.*/ {
		date = $4 # [29/Mar/2017:06:36:22
		sub("\\[", "", date)
		sub(":", " ", date)
		split(date, a, " ")
		date = a[1]
		time = a[2]
		split(date, a, "/")
		date = a[3] "-" a[2] "-" a[1]
		op = $6
		gsub("\"", "", op)
		path = $7
		rc = $9
		bytes = $10
		rt = $(NF)
		gsub("\"", "", rt)
		print date, time, rt, 0, 0, bytes, path, rc, op 
	}
'
}

say() {
	echo "$@" 1>&2
}

main "$@"
